# Generated by Django 5.2.5 on 2025-08-13 16:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('mobile_phone', models.CharField(help_text='Requerido para notificaciones importantes', max_length=17, validators=[django.core.validators.RegexValidator(message="Formato: '+999999999'. Hasta 15 dígitos.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Teléfono celular')),
                ('city', models.CharField(max_length=100, verbose_name='Ciudad de residencia')),
                ('work_environment', models.JSONField(default=list, help_text='Puede seleccionar múltiples opciones', verbose_name='Ámbito de trabajo')),
                ('institution_name', models.CharField(blank=True, help_text='Opcional - Si aplica', max_length=200, verbose_name='Nombre de la institución')),
                ('professional_id', models.CharField(help_text='Médico, Psicólogo o profesión relacionada - REQUERIDO', max_length=50, verbose_name='Cédula profesional')),
                ('specialty_id', models.CharField(blank=True, help_text='Si aplica', max_length=50, verbose_name='Cédula de especialidad')),
                ('profession_type', models.CharField(help_text='Ej: Médico, Psicólogo, Psiquiatra, etc.', max_length=100, verbose_name='Profesión')),
                ('discovery_source', models.CharField(choices=[('google', 'Google/Búsqueda web'), ('colleague', 'Recomendación de colega'), ('social_media', 'Redes sociales'), ('conference', 'Conferencia/Congreso'), ('university', 'Universidad/Institución educativa'), ('publication', 'Publicación científica'), ('other', 'Otro')], max_length=20, verbose_name='¿Cómo encontró ClinimetrixPro?')),
                ('discovery_other', models.CharField(blank=True, max_length=200, verbose_name='Otro - especificar')),
                ('theme_preference', models.CharField(choices=[('auto', 'Automático (sistema)'), ('light', 'Claro siempre'), ('dark', 'Oscuro siempre'), ('disabled', 'Desactivar tema dinámico')], default='auto', max_length=20, verbose_name='Preferencia de tema')),
                ('default_landing_page', models.CharField(choices=[('dashboard', 'Dashboard'), ('patients', 'Lista de Pacientes'), ('scales', 'Catálogo de Escalas'), ('assessments', 'Evaluaciones')], default='dashboard', max_length=20, verbose_name='Página de entrada predeterminada')),
                ('profile_complete', models.BooleanField(default=False, verbose_name='Perfil completo')),
                ('credentials_verified', models.BooleanField(default=False, verbose_name='Credenciales verificadas')),
                ('verification_notes', models.TextField(blank=True, help_text='Para uso interno del equipo de revisión', verbose_name='Notas de verificación')),
                ('data_processing_consent', models.BooleanField(default=False, verbose_name='Consentimiento procesamiento de datos')),
                ('marketing_consent', models.BooleanField(default=False, verbose_name='Acepta comunicaciones de marketing')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil Médico',
                'verbose_name_plural': 'Perfiles Médicos',
                'db_table': 'clinimetrix_medical_profiles',
            },
        ),
    ]
