[phases.setup]
nixPkgs = ['nodejs_18', 'npm-9_x']

[phases.install]
cmds = ['npm ci']

[phases.build]
cmds = [
  'npx prisma generate',
  'echo "Checking for JSON files..."',
  'ls -la shared/validators/ || echo "validators directory not found"',
  'find . -name "clinimetrix-template-schema.json" || echo "Schema file not found"',
  'cp -r shared /app/ || true',
  'ls -la /app/shared/validators/ || echo "Target validators directory not found"'
]

[start]
cmd = 'npm start'