# HAPI FHIR Server Configuration for MindHub Healthcare Platform
# Supports HL7 FHIR R4 with Mexican healthcare compliance

spring:
  application:
    name: mindhub-fhir-server
  
  # Database Configuration
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:mindhub_fhir}
    username: ${DB_USERNAME:mindhub_fhir}
    password: ${DB_PASSWORD:secure_password}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  
  # JPA Configuration
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQL10Dialect
      hibernate.search.backend.directory.root: ./target/lucenefiles
      hibernate.search.backend.lucene_version: LUCENE_CURRENT
      hibernate.jdbc.batch_size: 20
      hibernate.cache.use_query_cache: false
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_structured_entries: false
      hibernate.cache.use_minimal_puts: false
      hibernate.search.model_mapping: ca.uhn.fhir.jpa.search.LuceneSearchMappingFactory
    show-sql: ${SHOW_SQL:false}
  
  # Redis Configuration for Caching
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}
    timeout: 2000ms
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0

# HAPI FHIR Configuration
hapi:
  fhir:
    version: R4
    server:
      path: /fhir/R4/*
      name: MindHub Healthcare FHIR Server
      version: 1.0.0
      implementation_description: "HL7 FHIR R4 Server for MindHub Healthcare Platform with Mexican compliance"
    
    # Validation Configuration
    validation:
      enabled: true
      request_only: false
      
    # Narrative Generation
    narrative:
      enabled: true
      
    # CORS Configuration
    cors:
      enabled: true
      allowed_origin:
        - https://app.mindhub.com
        - https://admin.mindhub.com
        - https://mobile.mindhub.com
        - http://localhost:3000
        - http://localhost:3001
      allow_credentials: true
      allowed_headers:
        - "Authorization"
        - "Content-Type"
        - "X-Requested-With"
        - "X-FHIR-Starter"
      allowed_methods:
        - GET
        - POST
        - PUT
        - PATCH
        - DELETE
        - OPTIONS
    
    # Bundle/Transaction Configuration
    bundle:
      allow_inline_match_url_references: true
      enforce_referential_integrity_on_write: true
    
    # Subscription Configuration
    subscription:
      enabled: true
      resthook_enabled: true
      websocket_enabled: true
      email_enabled: false
      
    # Bulk Data Export
    bulk_export:
      enabled: true
      
    # JSON Parser Configuration
    json_parser:
      dont_encode_elements:
        - "*.meta.versionId"
        - "*.meta.lastUpdated"
      
    # Search Configuration
    search:
      # Maximum number of search results returned in a single page
      max_page_size: 200
      default_page_size: 20
      # Enable searching with lastUpdated parameter
      lastupdated_enabled: true
      # Respect forwarded headers for pagination links
      respect_forwarded_headers: true

# MindHub Specific Configuration
mindhub:
  fhir:
    # Mexican Healthcare Profiles
    profiles:
      mexican_extensions: true
      nom024_compliance: true
      cofepris_ready: true
      
    # Terminology Services
    terminology:
      # International standards
      snomed_ct: true
      loinc: true
      icd10: true
      
      # Mexican specific codes
      mexican_codes: true
      cie10_mexico: true
      
      # Terminology server endpoint
      tx_server_url: ${TX_SERVER_URL:http://tx.fhir.org/r4}
      
    # Security Configuration
    security:
      # SMART on FHIR
      smart_on_fhir: true
      oauth_server: ${OAUTH_SERVER:https://auth.mindhub.com}
      
      # CORS for development
      cors_development: ${CORS_DEV:false}
      
      # Rate limiting
      rate_limiting:
        enabled: true
        requests_per_minute: 1000
        
    # Audit Configuration
    audit:
      enabled: true
      log_all_requests: true
      nom024_compliance: true
      
      # Audit event storage
      store_in_database: true
      store_in_elasticsearch: true
      
    # Performance Configuration
    performance:
      # Database optimization
      enable_index_missing_fields: true
      normalize_terminology_for_search: true
      
      # Cache settings
      cache_enabled: true
      cache_ttl_minutes: 15
      
      # Async processing
      async_enabled: true
      
    # Integration Settings
    integrations:
      expedix:
        enabled: true
        webhook_url: ${EXPEDIX_WEBHOOK:http://localhost:3002/webhook/fhir}
        
      clinimetrix:
        enabled: true
        webhook_url: ${CLINIMETRIX_WEBHOOK:http://localhost:3003/webhook/fhir}
        
      formx:
        enabled: true
        webhook_url: ${FORMX_WEBHOOK:http://localhost:3004/webhook/fhir}

# Logging Configuration
logging:
  level:
    ca.uhn.fhir.jpa: ${FHIR_LOG_LEVEL:INFO}
    org.springframework.web: ${SPRING_LOG_LEVEL:INFO}
    org.hibernate.SQL: ${SQL_LOG_LEVEL:WARN}
    org.hibernate.type.descriptor.sql: ${SQL_PARAM_LOG_LEVEL:WARN}
    org.elasticsearch: ${ES_LOG_LEVEL:WARN}
    com.mindhub.fhir: ${MINDHUB_LOG_LEVEL:DEBUG}
  
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  
  file:
    name: logs/mindhub-fhir-server.log
    max-size: 100MB
    max-history: 30

# Management and Monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

# Server Configuration
server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /
  compression:
    enabled: true
    mime-types: application/json,application/fhir+json,application/xml,application/fhir+xml
  
  # SSL Configuration (for production)
  ssl:
    enabled: ${SSL_ENABLED:false}
    key-store: ${SSL_KEYSTORE:}
    key-store-password: ${SSL_KEYSTORE_PASSWORD:}
    key-store-type: ${SSL_KEYSTORE_TYPE:PKCS12}

# Custom MindHub FHIR Properties
mx:
  fhir:
    # NOM-024 Compliance Features
    nom024:
      digital_signature_required: true
      audit_trail_retention_years: 10
      emergency_access_enabled: true
      patient_consent_required: true
      
    # COFEPRIS Requirements
    cofepris:
      software_classification: "Class_II_Medical_Device"
      quality_management: "ISO_13485"
      risk_management: "ISO_14971"
      
    # Mexican Geographic Data
    geography:
      default_country: "MX"
      state_validation: true
      municipality_support: true
      
    # Language Support
    language:
      default: "es-MX"
      supported: ["es-MX", "en-US"]
      
    # Custom Extensions
    extensions:
      curp_validation: true
      rfc_validation: true
      nss_validation: true
      emergency_contact_required: true
      
    # Data Retention Policies
    retention:
      patient_data_years: 10
      audit_logs_years: 10
      deleted_resources_days: 30