# Generated by Django 5.2.1 on 2025-08-20 12:24

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expedix', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('appointment_number', models.CharField(max_length=50, unique=True)),
                ('appointment_date', models.DateTimeField()),
                ('duration', models.IntegerField(help_text='Duration in minutes (15-480)', validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(480)])),
                ('appointment_type', models.CharField(choices=[('consultation', 'Consulta'), ('follow_up', 'Seguimiento'), ('emergency', 'Emergencia'), ('therapy', 'Terapia'), ('evaluation', 'Evaluación'), ('medication_review', 'Revisión de medicación')], max_length=50)),
                ('reason', models.CharField(blank=True, max_length=200, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Programada'), ('confirmed', 'Confirmada'), ('cancelled', 'Cancelada'), ('no_show', 'No se presentó'), ('completed', 'Completada'), ('rescheduled', 'Reprogramada')], default='scheduled', max_length=20)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('reschedule_requested', models.BooleanField(default=False)),
                ('requires_preparation', models.BooleanField(default=False)),
                ('preparation_instructions', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_appointments', to='expedix.user')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_appointments', to='expedix.user')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='expedix.patient')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provider_appointments', to='expedix.user')),
                ('scheduled_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scheduled_appointments', to='expedix.user')),
            ],
            options={
                'db_table': 'appointments',
            },
        ),
        migrations.CreateModel(
            name='AppointmentConfirmation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('confirmation_type', models.CharField(choices=[('patient', 'Paciente'), ('staff', 'Personal'), ('automatic', 'Automática')], max_length=20)),
                ('confirmation_method', models.CharField(choices=[('phone', 'Teléfono'), ('email', 'Email'), ('sms', 'SMS'), ('in_person', 'En persona'), ('online', 'En línea')], max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmations', to='agenda.appointment')),
                ('confirmed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='expedix.user')),
            ],
            options={
                'db_table': 'appointment_confirmations',
            },
        ),
        migrations.CreateModel(
            name='AppointmentHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('SCHEDULED', 'Programada'), ('CONFIRMED', 'Confirmada'), ('CANCELLED', 'Cancelada'), ('RESCHEDULED', 'Reprogramada'), ('COMPLETED', 'Completada'), ('NO_SHOW', 'No se presentó'), ('MODIFIED', 'Modificada')], max_length=20)),
                ('changes', models.JSONField(help_text='Details of changes made')),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='agenda.appointment')),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='expedix.user')),
            ],
            options={
                'db_table': 'appointment_history',
            },
        ),
        migrations.CreateModel(
            name='ProviderSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weekday', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('break_start', models.TimeField(blank=True, null=True)),
                ('break_end', models.TimeField(blank=True, null=True)),
                ('slot_duration', models.IntegerField(default=60, help_text='Default slot duration in minutes')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_schedules', to='expedix.user')),
            ],
            options={
                'db_table': 'provider_schedules',
            },
        ),
        migrations.CreateModel(
            name='ScheduleBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('block_type', models.CharField(choices=[('vacation', 'Vacaciones'), ('holiday', 'Día festivo'), ('sick_leave', 'Licencia médica'), ('special_hours', 'Horario especial'), ('unavailable', 'No disponible')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('all_day', models.BooleanField(default=True)),
                ('reason', models.CharField(blank=True, max_length=200, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_blocks', to='expedix.user')),
            ],
            options={
                'db_table': 'schedule_blocks',
            },
        ),
        migrations.CreateModel(
            name='WaitingList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('appointment_type', models.CharField(choices=[('consultation', 'Consulta'), ('follow_up', 'Seguimiento'), ('emergency', 'Emergencia'), ('therapy', 'Terapia'), ('evaluation', 'Evaluación'), ('medication_review', 'Revisión de medicación')], max_length=50)),
                ('preferred_date_start', models.DateField(blank=True, null=True)),
                ('preferred_date_end', models.DateField(blank=True, null=True)),
                ('preferred_time_start', models.TimeField(blank=True, null=True)),
                ('preferred_time_end', models.TimeField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('normal', 'Normal'), ('high', 'Alta'), ('urgent', 'Urgente')], default='normal', max_length=10)),
                ('status', models.CharField(choices=[('waiting', 'En espera'), ('contacted', 'Contactado'), ('scheduled', 'Programado'), ('cancelled', 'Cancelado'), ('expired', 'Expirado')], default='waiting', max_length=20)),
                ('reason', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True, null=True)),
                ('contacted_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='waiting_list_entries_added', to='expedix.user')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waiting_list_entries', to='expedix.patient')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waiting_list', to='expedix.user')),
            ],
            options={
                'db_table': 'waiting_list',
            },
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['patient'], name='appointment_patient_75a4eb_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['provider'], name='appointment_provide_7523ed_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['appointment_date'], name='appointment_appoint_8b74ac_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['status'], name='appointment_status_9fecd6_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['appointment_number'], name='appointment_appoint_e7d91b_idx'),
        ),
        migrations.AddIndex(
            model_name='appointmentconfirmation',
            index=models.Index(fields=['appointment'], name='appointment_appoint_dfed55_idx'),
        ),
        migrations.AddIndex(
            model_name='appointmentconfirmation',
            index=models.Index(fields=['confirmed_at'], name='appointment_confirm_b0d54e_idx'),
        ),
        migrations.AddIndex(
            model_name='appointmentconfirmation',
            index=models.Index(fields=['confirmation_type'], name='appointment_confirm_05e25e_idx'),
        ),
        migrations.AddIndex(
            model_name='appointmenthistory',
            index=models.Index(fields=['appointment'], name='appointment_appoint_8a2fcd_idx'),
        ),
        migrations.AddIndex(
            model_name='appointmenthistory',
            index=models.Index(fields=['created_at'], name='appointment_created_cc5ef7_idx'),
        ),
        migrations.AddIndex(
            model_name='appointmenthistory',
            index=models.Index(fields=['action'], name='appointment_action_11d961_idx'),
        ),
        migrations.AddIndex(
            model_name='providerschedule',
            index=models.Index(fields=['provider'], name='provider_sc_provide_50e59e_idx'),
        ),
        migrations.AddIndex(
            model_name='providerschedule',
            index=models.Index(fields=['weekday'], name='provider_sc_weekday_3d3a7d_idx'),
        ),
        migrations.AddIndex(
            model_name='providerschedule',
            index=models.Index(fields=['is_active'], name='provider_sc_is_acti_f93ee9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='providerschedule',
            unique_together={('provider', 'weekday', 'start_time')},
        ),
        migrations.AddIndex(
            model_name='scheduleblock',
            index=models.Index(fields=['provider'], name='schedule_bl_provide_882755_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduleblock',
            index=models.Index(fields=['start_date', 'end_date'], name='schedule_bl_start_d_5d3f9b_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduleblock',
            index=models.Index(fields=['block_type'], name='schedule_bl_block_t_1141c6_idx'),
        ),
        migrations.AddIndex(
            model_name='waitinglist',
            index=models.Index(fields=['patient'], name='waiting_lis_patient_19b0b1_idx'),
        ),
        migrations.AddIndex(
            model_name='waitinglist',
            index=models.Index(fields=['provider'], name='waiting_lis_provide_969b0c_idx'),
        ),
        migrations.AddIndex(
            model_name='waitinglist',
            index=models.Index(fields=['status'], name='waiting_lis_status_32bb5f_idx'),
        ),
        migrations.AddIndex(
            model_name='waitinglist',
            index=models.Index(fields=['priority'], name='waiting_lis_priorit_628028_idx'),
        ),
        migrations.AddIndex(
            model_name='waitinglist',
            index=models.Index(fields=['created_at'], name='waiting_lis_created_709a16_idx'),
        ),
    ]
