# Generated by Django 4.2.11 on 2025-09-13 07:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expedix', '0004_medicationdatabase_prescriptionmedication_profile_and_more'),
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient_id', models.UUIDField()),
                ('professional_id', models.UUIDField()),
                ('appointment_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('appointment_type', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('internal_notes', models.TextField(blank=True, null=True)),
                ('confirmation_sent', models.BooleanField(blank=True, null=True)),
                ('confirmation_date', models.DateTimeField(blank=True, null=True)),
                ('is_recurring', models.BooleanField(blank=True, null=True)),
                ('recurring_pattern', models.JSONField(blank=True, null=True)),
                ('reminder_sent', models.BooleanField(blank=True, null=True)),
                ('reminder_date', models.DateTimeField(blank=True, null=True)),
                ('clinic_id', models.BooleanField(default=False)),
                ('user_id', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'db_table': 'appointments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WaitingList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('clinic_id', models.BooleanField(default=False, help_text='true = clinic waiting list, false = individual waiting list')),
                ('user_id', models.UUIDField(blank=True, help_text='Owner of the waiting list entry', null=True)),
                ('appointment_type', models.CharField(choices=[('consultation', 'Consulta'), ('follow_up', 'Seguimiento'), ('emergency', 'Emergencia'), ('therapy', 'Terapia'), ('evaluation', 'Evaluación'), ('medication_review', 'Revisión de medicación')], max_length=50)),
                ('preferred_date_start', models.DateField(blank=True, null=True)),
                ('preferred_date_end', models.DateField(blank=True, null=True)),
                ('preferred_time_start', models.TimeField(blank=True, null=True)),
                ('preferred_time_end', models.TimeField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('normal', 'Normal'), ('high', 'Alta'), ('urgent', 'Urgente')], default='normal', max_length=10)),
                ('status', models.CharField(choices=[('waiting', 'En espera'), ('contacted', 'Contactado'), ('scheduled', 'Programado'), ('cancelled', 'Cancelado'), ('expired', 'Expirado')], default='waiting', max_length=20)),
                ('reason', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True, null=True)),
                ('contacted_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='waiting_list_entries_added', to='expedix.profile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waiting_list_entries', to='expedix.patient')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waiting_list', to='expedix.profile')),
            ],
            options={
                'db_table': 'waiting_list',
                'indexes': [models.Index(fields=['patient'], name='waiting_lis_patient_19b0b1_idx'), models.Index(fields=['provider'], name='waiting_lis_provide_969b0c_idx'), models.Index(fields=['status'], name='waiting_lis_status_32bb5f_idx'), models.Index(fields=['priority'], name='waiting_lis_priorit_628028_idx'), models.Index(fields=['created_at'], name='waiting_lis_created_709a16_idx')],
            },
        ),
        migrations.CreateModel(
            name='ScheduleBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('clinic_id', models.BooleanField(default=False, help_text='true = clinic block, false = individual block')),
                ('user_id', models.UUIDField(blank=True, help_text='Owner of the schedule block', null=True)),
                ('block_type', models.CharField(choices=[('vacation', 'Vacaciones'), ('holiday', 'Día festivo'), ('sick_leave', 'Licencia médica'), ('special_hours', 'Horario especial'), ('unavailable', 'No disponible')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('all_day', models.BooleanField(default=True)),
                ('reason', models.CharField(blank=True, max_length=200, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_blocks', to='expedix.profile')),
            ],
            options={
                'db_table': 'schedule_blocks',
                'indexes': [models.Index(fields=['provider'], name='schedule_bl_provide_882755_idx'), models.Index(fields=['start_date', 'end_date'], name='schedule_bl_start_d_5d3f9b_idx'), models.Index(fields=['block_type'], name='schedule_bl_block_t_1141c6_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProviderSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('clinic_id', models.BooleanField(default=False, help_text='true = clinic schedule, false = individual schedule')),
                ('user_id', models.UUIDField(blank=True, help_text='Owner of the schedule', null=True)),
                ('weekday', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('break_start', models.TimeField(blank=True, null=True)),
                ('break_end', models.TimeField(blank=True, null=True)),
                ('slot_duration', models.IntegerField(default=60, help_text='Default slot duration in minutes')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_schedules', to='expedix.profile')),
            ],
            options={
                'db_table': 'provider_schedules',
                'indexes': [models.Index(fields=['provider'], name='provider_sc_provide_50e59e_idx'), models.Index(fields=['weekday'], name='provider_sc_weekday_3d3a7d_idx'), models.Index(fields=['is_active'], name='provider_sc_is_acti_f93ee9_idx')],
                'unique_together': {('provider', 'weekday', 'start_time')},
            },
        ),
        migrations.CreateModel(
            name='AppointmentHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('clinic_id', models.BooleanField(default=False, help_text='true = clinic appointment, false = individual appointment')),
                ('user_id', models.UUIDField(blank=True, help_text='Owner of the appointment history', null=True)),
                ('action', models.CharField(choices=[('SCHEDULED', 'Programada'), ('CONFIRMED', 'Confirmada'), ('CANCELLED', 'Cancelada'), ('RESCHEDULED', 'Reprogramada'), ('COMPLETED', 'Completada'), ('NO_SHOW', 'No se presentó'), ('MODIFIED', 'Modificada')], max_length=20)),
                ('changes', models.JSONField(help_text='Details of changes made')),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='agenda.appointment')),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='expedix.profile')),
            ],
            options={
                'db_table': 'appointment_history',
                'indexes': [models.Index(fields=['appointment'], name='appointment_appoint_8a2fcd_idx'), models.Index(fields=['created_at'], name='appointment_created_cc5ef7_idx'), models.Index(fields=['action'], name='appointment_action_11d961_idx')],
            },
        ),
        migrations.CreateModel(
            name='AppointmentConfirmation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('clinic_id', models.BooleanField(default=False, help_text='true = clinic confirmation, false = individual confirmation')),
                ('user_id', models.UUIDField(blank=True, help_text='Owner of the confirmation', null=True)),
                ('confirmation_type', models.CharField(choices=[('patient', 'Paciente'), ('staff', 'Personal'), ('automatic', 'Automática')], max_length=20)),
                ('confirmation_method', models.CharField(choices=[('phone', 'Teléfono'), ('email', 'Email'), ('sms', 'SMS'), ('in_person', 'En persona'), ('online', 'En línea')], max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmations', to='agenda.appointment')),
                ('confirmed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='expedix.profile')),
            ],
            options={
                'db_table': 'appointment_confirmations',
                'indexes': [models.Index(fields=['appointment'], name='appointment_appoint_dfed55_idx'), models.Index(fields=['confirmed_at'], name='appointment_confirm_b0d54e_idx'), models.Index(fields=['confirmation_type'], name='appointment_confirm_05e25e_idx')],
            },
        ),
    ]
