# Generated by Django 5.2.1 on 2025-08-20 12:24

import django.core.validators
import django.db.models.deletion
import resources.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expedix', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, max_length=100, null=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='resources.resourcecategory')),
            ],
            options={
                'verbose_name': 'Categoría de Recursos',
                'verbose_name_plural': 'Categorías de Recursos',
                'db_table': 'resource_categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(upload_to=resources.models.ResourceUploadPath('originals'), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png', 'gif', 'txt', 'mp4', 'mp3'])])),
                ('original_filename', models.CharField(max_length=500)),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('image', 'Imagen'), ('document', 'Documento'), ('video', 'Video'), ('audio', 'Audio'), ('other', 'Otro')], max_length=50)),
                ('file_size', models.BigIntegerField()),
                ('mime_type', models.CharField(max_length=100)),
                ('library_type', models.CharField(choices=[('public', 'Público'), ('private', 'Privado'), ('premium', 'Premium')], default='private', max_length=20)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=resources.models.ResourceUploadPath('thumbnails'))),
                ('content_hash', models.CharField(help_text='SHA-256 hash for duplicate detection', max_length=64, unique=True)),
                ('full_text_content', models.TextField(blank=True, help_text='Extracted text content for search', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('send_count', models.IntegerField(default=0)),
                ('view_count', models.IntegerField(default=0)),
                ('download_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_resources', to='expedix.user')),
                ('upload_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_resources', to='expedix.user')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to='resources.resourcecategory')),
            ],
            options={
                'db_table': 'resources',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResourceCollection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_collections', to='expedix.user')),
            ],
            options={
                'db_table': 'resource_collections',
            },
        ),
        migrations.CreateModel(
            name='ResourceCollectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(default=0)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='resources.resourcecollection')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_items', to='resources.resource')),
            ],
            options={
                'db_table': 'resource_collection_items',
                'ordering': ['sort_order', 'added_at'],
            },
        ),
        migrations.CreateModel(
            name='ResourceEmailTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=500)),
                ('body_html', models.TextField()),
                ('body_text', models.TextField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_templates', to='expedix.user')),
            ],
            options={
                'db_table': 'resource_email_templates',
            },
        ),
        migrations.CreateModel(
            name='ResourceSend',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('send_method', models.CharField(choices=[('email', 'Email'), ('download', 'Descarga'), ('patient-portal', 'Portal del Paciente')], max_length=20)),
                ('watermark_applied', models.BooleanField(default=False)),
                ('customizations', models.JSONField(blank=True, default=dict)),
                ('delivery_status', models.CharField(choices=[('pending', 'Pendiente'), ('sent', 'Enviado'), ('delivered', 'Entregado'), ('failed', 'Fallido')], default='sent', max_length=20)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('download_count', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('email_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resources.resourceemailtemplate')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_sends', to='expedix.patient')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sends', to='resources.resource')),
                ('sent_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='expedix.user')),
            ],
            options={
                'db_table': 'resource_sends',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='ResourceAccessLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('action', models.CharField(choices=[('view', 'Ver'), ('download', 'Descargar'), ('print', 'Imprimir')], max_length=20)),
                ('resource_send', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='resources.resourcesend')),
            ],
            options={
                'db_table': 'resource_access_logs',
                'ordering': ['-accessed_at'],
            },
        ),
        migrations.CreateModel(
            name='WatermarkTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('text', 'Texto'), ('image', 'Imagen'), ('combined', 'Combinado')], max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=resources.models.ResourceUploadPath('watermarks'))),
                ('text_content', models.CharField(blank=True, max_length=500, null=True)),
                ('position', models.CharField(choices=[('top-left', 'Superior Izquierda'), ('top-center', 'Superior Centro'), ('top-right', 'Superior Derecha'), ('center', 'Centro'), ('bottom-left', 'Inferior Izquierda'), ('bottom-center', 'Inferior Centro'), ('bottom-right', 'Inferior Derecha')], default='bottom-right', max_length=20)),
                ('opacity', models.DecimalField(decimal_places=2, default=0.5, max_digits=3)),
                ('font_size', models.IntegerField(default=12)),
                ('font_color', models.CharField(default='#000000', max_length=7)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watermark_templates', to='expedix.user')),
            ],
            options={
                'db_table': 'watermark_templates',
            },
        ),
        migrations.AddField(
            model_name='resourcesend',
            name='watermark_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resources.watermarktemplate'),
        ),
        migrations.AddIndex(
            model_name='resourcecategory',
            index=models.Index(fields=['parent'], name='resource_ca_parent__811389_idx'),
        ),
        migrations.AddIndex(
            model_name='resourcecategory',
            index=models.Index(fields=['sort_order'], name='resource_ca_sort_or_057648_idx'),
        ),
        migrations.AddIndex(
            model_name='resourcecategory',
            index=models.Index(fields=['is_active'], name='resource_ca_is_acti_20f31d_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['library_type'], name='resources_library_a2f10b_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['owner'], name='resources_owner_i_aff52f_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['category'], name='resources_categor_3512bc_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['created_at'], name='resources_created_3c8efb_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['is_active'], name='resources_is_acti_e1ba4f_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['file_type'], name='resources_file_ty_51644c_idx'),
        ),
        migrations.AddIndex(
            model_name='resourcecollection',
            index=models.Index(fields=['user'], name='resource_co_user_id_61080d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='resourcecollectionitem',
            unique_together={('collection', 'resource')},
        ),
        migrations.AddIndex(
            model_name='resourceemailtemplate',
            index=models.Index(fields=['user'], name='resource_em_user_id_fc4e73_idx'),
        ),
        migrations.AddIndex(
            model_name='resourceaccesslog',
            index=models.Index(fields=['resource_send'], name='resource_ac_resourc_d0585b_idx'),
        ),
        migrations.AddIndex(
            model_name='resourceaccesslog',
            index=models.Index(fields=['accessed_at'], name='resource_ac_accesse_ff5aa6_idx'),
        ),
        migrations.AddIndex(
            model_name='watermarktemplate',
            index=models.Index(fields=['user', 'is_default'], name='watermark_t_user_id_f39ee8_idx'),
        ),
        migrations.AddIndex(
            model_name='resourcesend',
            index=models.Index(fields=['patient'], name='resource_se_patient_805a4f_idx'),
        ),
        migrations.AddIndex(
            model_name='resourcesend',
            index=models.Index(fields=['resource'], name='resource_se_resourc_388462_idx'),
        ),
        migrations.AddIndex(
            model_name='resourcesend',
            index=models.Index(fields=['sent_at'], name='resource_se_sent_at_8921dc_idx'),
        ),
        migrations.AddIndex(
            model_name='resourcesend',
            index=models.Index(fields=['delivery_status'], name='resource_se_deliver_7d1b2e_idx'),
        ),
    ]
