# Generated by Django 4.2.11 on 2025-08-25 02:13

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('psychometric_scales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScaleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#1E40AF', max_length=7)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoría de escala',
                'verbose_name_plural': 'Categorías de escalas',
                'db_table': 'clinimetrix_scale_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ScaleTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('tag_type', models.CharField(choices=[('diagnostic', 'Diagnóstico'), ('population', 'Población'), ('domain', 'Dominio'), ('specialty', 'Especialidad'), ('custom', 'Personalizado')], default='custom', max_length=20)),
                ('color', models.CharField(default='#6B7280', help_text='Color hex para el tag', max_length=7)),
                ('description', models.TextField(blank=True)),
                ('is_system', models.BooleanField(default=False, help_text='Tag del sistema (no editable por usuarios)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Usuario que creó el tag', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tag de escala',
                'verbose_name_plural': 'Tags de escalas',
                'db_table': 'clinimetrix_scale_tags',
                'ordering': ['tag_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PsychometricScale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('abbreviation', models.CharField(max_length=20, unique=True)),
                ('authors', models.JSONField(default=list)),
                ('year', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('indication', models.TextField(help_text='Indicaciones clínicas de uso')),
                ('population', models.CharField(choices=[('adult', 'Adultos'), ('adolescent', 'Adolescentes'), ('child', 'Niños'), ('elderly', 'Adultos mayores'), ('all', 'Todas las edades')], default='adult', max_length=20)),
                ('application_type', models.CharField(choices=[('auto', 'Autoaplicada'), ('hetero', 'Heteroaplicada'), ('both', 'Ambas')], default='auto', max_length=10)),
                ('estimated_duration_minutes', models.PositiveIntegerField(default=10)),
                ('total_items', models.PositiveIntegerField()),
                ('json_file_path', models.CharField(max_length=255)),
                ('reliability_alpha', models.FloatField(blank=True, help_text="Cronbach's Alpha", null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('sensitivity', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('specificity', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('test_retest_reliability', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('is_active', models.BooleanField(default=True)),
                ('is_validated', models.BooleanField(default=False)),
                ('requires_training', models.CharField(choices=[('minimal', 'Mínimo'), ('moderate', 'Moderado'), ('high', 'Alto'), ('very_high', 'Muy alto')], default='minimal', max_length=20)),
                ('copyright_info', models.TextField(blank=True)),
                ('license_required', models.BooleanField(default=False)),
                ('primary_reference', models.TextField(blank=True)),
                ('additional_references', models.JSONField(default=list)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scales', to='psychometric_scales.scalecategory')),
                ('tags', models.ManyToManyField(blank=True, help_text='Tags para categorizar y filtrar la escala', related_name='scales', to='psychometric_scales.scaletag')),
            ],
            options={
                'verbose_name': 'Escala psicométrica',
                'verbose_name_plural': 'Escalas psicométricas',
                'db_table': 'clinimetrix_registry',
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='scaletag',
            index=models.Index(fields=['tag_type'], name='clinimetrix_tag_typ_15a739_idx'),
        ),
        migrations.AddIndex(
            model_name='scaletag',
            index=models.Index(fields=['slug'], name='clinimetrix_slug_51a685_idx'),
        ),
        migrations.AddIndex(
            model_name='psychometricscale',
            index=models.Index(fields=['abbreviation'], name='clinimetrix_abbrevi_51d4d4_idx'),
        ),
        migrations.AddIndex(
            model_name='psychometricscale',
            index=models.Index(fields=['category'], name='clinimetrix_categor_14c965_idx'),
        ),
        migrations.AddIndex(
            model_name='psychometricscale',
            index=models.Index(fields=['is_active'], name='clinimetrix_is_acti_9bb064_idx'),
        ),
    ]
