# Generated by Django 5.2.5 on 2025-08-15 00:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychometric_scales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScaleTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('tag_type', models.CharField(choices=[('diagnostic', 'Diagnóstico'), ('population', 'Población'), ('domain', 'Dominio'), ('specialty', 'Especialidad'), ('custom', 'Personalizado')], default='custom', max_length=20)),
                ('color', models.CharField(default='#6B7280', help_text='Color hex para el tag', max_length=7)),
                ('description', models.TextField(blank=True)),
                ('is_system', models.BooleanField(default=False, help_text='Tag del sistema (no editable por usuarios)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Usuario que creó el tag', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tag de escala',
                'verbose_name_plural': 'Tags de escalas',
                'db_table': 'clinimetrix_scale_tags',
                'ordering': ['tag_type', 'name'],
            },
        ),
        migrations.AddField(
            model_name='psychometricscale',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Tags para categorizar y filtrar la escala', related_name='scales', to='psychometric_scales.scaletag'),
        ),
        migrations.AddIndex(
            model_name='scaletag',
            index=models.Index(fields=['tag_type'], name='clinimetrix_tag_typ_15a739_idx'),
        ),
        migrations.AddIndex(
            model_name='scaletag',
            index=models.Index(fields=['slug'], name='clinimetrix_slug_51a685_idx'),
        ),
    ]
