# Generated by Django 5.2.1 on 2025-08-21 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psychometric_scales', '0002_scaletag_psychometricscale_tags_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='psychometricscale',
            new_name='clinimetrix_abbrevi_51d4d4_idx',
            old_name='clinimetrix_abbrevi_cadffd_idx',
        ),
        migrations.RenameIndex(
            model_name='psychometricscale',
            new_name='clinimetrix_categor_14c965_idx',
            old_name='clinimetrix_categor_14d542_idx',
        ),
        migrations.RenameIndex(
            model_name='psychometricscale',
            new_name='clinimetrix_is_acti_9bb064_idx',
            old_name='clinimetrix_is_acti_758600_idx',
        ),
        migrations.AlterModelTable(
            name='psychometricscale',
            table='clinimetrix_registry',
        ),
    ]
