# Generated by Django 4.2.11 on 2025-09-13 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psychometric_scales', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='psychometricscale',
            options={'managed': False, 'ordering': ['name'], 'verbose_name': 'Escala psicométrica', 'verbose_name_plural': 'Escalas psicométricas'},
        ),
    ]
