/**
 * Mock data for development - simulates Supabase database data
 */

export const mockPatients = [
  {
    id: 'patient-001',
    medical_record_number: 'MRN-001',
    first_name: 'María José',
    last_name: 'González',
    paternal_last_name: 'Sánchez',
    maternal_last_name: 'López',
    date_of_birth: '1985-03-15',
    gender: 'female',
    email: 'maria.gonzalez@email.com',
    phone: '+52 55 1234 5678',
    address: 'Av. Reforma 123, Col. Centro',
    city: 'Ciudad de México',
    state: 'CDMX',
    postal_code: '06000',
    country: 'México',
    curp: 'GOSM850315MDFNLR04',
    blood_type: 'O+',
    allergies: ['Polen', 'Penicilina'],
    chronic_conditions: ['Hipertensión'],
    current_medications: ['Losartán 50mg'],
    emergency_contact_name: 'Juan González',
    emergency_contact_phone: '+52 55 8765 4321',
    emergency_contact_relationship: 'Esposo',
    consent_to_treatment: true,
    consent_to_data_processing: true,
    patient_category: 'general',
    is_active: true,
    created_by: 'demo-user-123',
    created_at: '2024-01-15T10:00:00.000Z',
    updated_at: '2024-01-15T10:00:00.000Z'
  },
  {
    id: 'patient-002',
    medical_record_number: 'MRN-002',
    first_name: 'Carlos',
    last_name: 'Rodríguez',
    paternal_last_name: 'Martínez',
    maternal_last_name: 'Hernández',
    date_of_birth: '1978-11-22',
    gender: 'male',
    email: 'carlos.rodriguez@email.com',
    phone: '+52 55 2345 6789',
    address: 'Calle Madero 456, Col. Roma Norte',
    city: 'Ciudad de México',
    state: 'CDMX',
    postal_code: '06700',
    country: 'México',
    curp: 'ROMC781122HDFDRR05',
    blood_type: 'A+',
    allergies: [],
    chronic_conditions: ['Diabetes Tipo 2'],
    current_medications: ['Metformina 850mg'],
    emergency_contact_name: 'Ana Rodríguez',
    emergency_contact_phone: '+52 55 3456 7890',
    emergency_contact_relationship: 'Esposa',
    consent_to_treatment: true,
    consent_to_data_processing: true,
    patient_category: 'general',
    is_active: true,
    created_by: 'demo-user-123',
    created_at: '2024-02-01T14:30:00.000Z',
    updated_at: '2024-02-01T14:30:00.000Z'
  },
  {
    id: 'patient-003',
    medical_record_number: 'MRN-003',
    first_name: 'Ana Patricia',
    last_name: 'Flores',
    paternal_last_name: 'García',
    maternal_last_name: 'Ruiz',
    date_of_birth: '1992-07-08',
    gender: 'female',
    email: 'ana.flores@email.com',
    phone: '+52 55 4567 8901',
    address: 'Av. Insurgentes 789, Col. Del Valle',
    city: 'Ciudad de México',
    state: 'CDMX',
    postal_code: '03100',
    country: 'México',
    curp: 'FOGA920708MDFRLR03',
    blood_type: 'B+',
    allergies: ['Mariscos'],
    chronic_conditions: [],
    current_medications: [],
    emergency_contact_name: 'Luis Flores',
    emergency_contact_phone: '+52 55 5678 9012',
    emergency_contact_relationship: 'Padre',
    consent_to_treatment: true,
    consent_to_data_processing: true,
    patient_category: 'general',
    is_active: true,
    created_by: 'demo-user-123',
    created_at: '2024-02-15T09:15:00.000Z',
    updated_at: '2024-02-15T09:15:00.000Z'
  },
  {
    id: 'patient-004',
    medical_record_number: 'MRN-004',
    first_name: 'Roberto',
    last_name: 'Méndez',
    paternal_last_name: 'Silva',
    maternal_last_name: 'Torres',
    date_of_birth: '1965-12-03',
    gender: 'male',
    email: 'roberto.mendez@email.com',
    phone: '+52 55 6789 0123',
    address: 'Calle Juárez 321, Col. Centro Histórico',
    city: 'Ciudad de México',
    state: 'CDMX',
    postal_code: '06060',
    country: 'México',
    curp: 'MESR651203HDFNLR01',
    blood_type: 'AB+',
    allergies: ['Aspirina'],
    chronic_conditions: ['Artritis'],
    current_medications: ['Ibuprofeno 400mg'],
    emergency_contact_name: 'Carmen Méndez',
    emergency_contact_phone: '+52 55 7890 1234',
    emergency_contact_relationship: 'Esposa',
    consent_to_treatment: true,
    consent_to_data_processing: true,
    patient_category: 'senior',
    is_active: true,
    created_by: 'demo-user-123',
    created_at: '2024-03-01T11:45:00.000Z',
    updated_at: '2024-03-01T11:45:00.000Z'
  },
  {
    id: 'patient-005',
    medical_record_number: 'MRN-005',
    first_name: 'Sofia',
    last_name: 'Vargas',
    paternal_last_name: 'Morales',
    maternal_last_name: 'Castro',
    date_of_birth: '2010-04-18',
    gender: 'female',
    email: 'contacto.sofia@email.com',
    phone: '+52 55 8901 2345',
    address: 'Av. Universidad 654, Col. Copilco',
    city: 'Ciudad de México',
    state: 'CDMX',
    postal_code: '04360',
    country: 'México',
    curp: 'VAMS100418MDFRSF02',
    blood_type: 'O-',
    allergies: [],
    chronic_conditions: [],
    current_medications: [],
    emergency_contact_name: 'Patricia Vargas',
    emergency_contact_phone: '+52 55 9012 3456',
    emergency_contact_relationship: 'Madre',
    consent_to_treatment: true,
    consent_to_data_processing: true,
    patient_category: 'pediatric',
    is_active: true,
    created_by: 'demo-user-123',
    created_at: '2024-03-15T16:20:00.000Z',
    updated_at: '2024-03-15T16:20:00.000Z'
  }
];

export const mockConsultations = [
  {
    id: 'consult-001',
    patient_id: 'patient-001',
    professional_id: 'demo-user-123',
    consultation_date: '2024-08-19T09:00:00.000Z',
    consultation_type: 'Primera consulta',
    chief_complaint: 'Dolor de cabeza recurrente',
    history_present_illness: 'Paciente refiere cefalea tensional desde hace 2 semanas',
    physical_examination: 'Examen neurológico normal',
    assessment: 'Cefalea tensional',
    plan: 'Analgésicos según necesidad, técnicas de relajación',
    notes: 'Seguimiento en 2 semanas',
    diagnosis_codes: ['G44.2'],
    follow_up_date: '2024-09-02',
    status: 'completed',
    created_at: '2024-08-19T09:00:00.000Z',
    updated_at: '2024-08-19T10:00:00.000Z'
  },
  {
    id: 'consult-002',
    patient_id: 'patient-002',
    professional_id: 'demo-user-123',
    consultation_date: '2024-08-19T10:30:00.000Z',
    consultation_type: 'Seguimiento',
    chief_complaint: 'Control de diabetes',
    history_present_illness: 'Paciente con diabetes tipo 2 en tratamiento',
    physical_examination: 'Peso estable, presión arterial normal',
    assessment: 'Diabetes mellitus tipo 2 controlada',
    plan: 'Continuar tratamiento actual',
    notes: 'Glucosa en ayunas 110 mg/dl',
    diagnosis_codes: ['E11.9'],
    follow_up_date: '2024-11-19',
    status: 'completed',
    created_at: '2024-08-19T10:30:00.000Z',
    updated_at: '2024-08-19T11:30:00.000Z'
  }
];

export const mockResources = [
  {
    id: 'resource-001',
    title: 'Guía de Depresión',
    description: 'Guía completa para el manejo de la depresión',
    filename: 'depression-guide.pdf',
    file_type: 'pdfs' as const,
    file_size: 2048000,
    mime_type: 'application/pdf',
    thumbnail_path: undefined,
    library_type: 'public' as const,
    category_name: 'Salud Mental',
    uploader_name: 'Dr. MindHub',
    created_at: '2024-01-01T00:00:00.000Z',
    tags: ['depresión', 'salud mental', 'tratamiento'],
    send_count: 15
  },
  {
    id: 'resource-002',
    title: 'Técnicas de Relajación',
    description: 'Video instructivo sobre técnicas de relajación',
    filename: 'relaxation-techniques.mp4',
    file_type: 'documents' as const,
    file_size: 15728640,
    mime_type: 'video/mp4',
    thumbnail_path: undefined,
    library_type: 'public' as const,
    category_name: 'Salud Mental',
    uploader_name: 'Dr. MindHub',
    created_at: '2024-01-15T00:00:00.000Z',
    tags: ['relajación', 'ansiedad', 'mindfulness'],
    send_count: 8
  },
  {
    id: 'resource-003',
    title: 'Registro de Signos Vitales',
    description: 'Plantilla para registro diario de signos vitales',
    filename: 'vital-signs-template.pdf',
    file_type: 'pdfs' as const,
    file_size: 512000,
    mime_type: 'application/pdf',
    thumbnail_path: undefined,
    library_type: 'private' as const,
    category_name: 'Medicina General',
    uploader_name: 'Mi Biblioteca',
    created_at: '2024-02-01T00:00:00.000Z',
    tags: ['signos vitales', 'registro', 'template'],
    send_count: 23
  },
  {
    id: 'resource-004',
    title: 'Infografía Higiene del Sueño',
    description: 'Consejos visuales para mejorar la calidad del sueño',
    filename: 'sleep-hygiene-infographic.png',
    file_type: 'images' as const,
    file_size: 1024000,
    mime_type: 'image/png',
    thumbnail_path: 'sleep-hygiene-thumb.png',
    library_type: 'public' as const,
    category_name: 'Salud Mental',
    uploader_name: 'Dr. MindHub',
    created_at: '2024-02-15T00:00:00.000Z',
    tags: ['sueño', 'higiene', 'infografía'],
    send_count: 12
  }
];

export const mockResourceCategories = [
  {
    id: 'cat-001',
    name: 'Salud Mental',
    slug: 'mental-health',
    description: 'Recursos relacionados con salud mental',
    icon: 'brain',
    color: '#3B82F6',
    is_active: true,
    created_at: '2024-01-01T00:00:00.000Z'
  },
  {
    id: 'cat-002',
    name: 'Medicina General',
    slug: 'general-medicine',
    description: 'Recursos de medicina general',
    icon: 'stethoscope',
    color: '#10B981',
    is_active: true,
    created_at: '2024-01-01T00:00:00.000Z'
  },
  {
    id: 'cat-003',
    name: 'Pediatría',
    slug: 'pediatrics',
    description: 'Recursos pediátricos',
    icon: 'baby',
    color: '#F59E0B',
    is_active: true,
    created_at: '2024-01-01T00:00:00.000Z'
  }
];