runtime: nodejs18
service: default

env_variables:
  NODE_ENV: production
  PORT: 8080
  
  # Auth0 Configuration
  AUTH0_DOMAIN: "your-domain.auth0.com"
  AUTH0_CLIENT_ID: "your-client-id"
  AUTH0_CLIENT_SECRET: "your-client-secret"
  AUTH0_AUDIENCE: "your-api-identifier"
  
  # Database Configuration
  DATABASE_URL: "postgresql://username:password@host:port/database"
  
  # Google Cloud Storage
  GOOGLE_CLOUD_PROJECT_ID: "your-project-id"
  GOOGLE_CLOUD_BUCKET: "your-bucket-name"
  
  # Encryption Keys
  ENCRYPTION_KEY: "your-encryption-key"
  JWT_SECRET: "your-jwt-secret"

automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.6
  target_throughput_utilization: 0.7

resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10

handlers:
  - url: /static
    static_dir: build/static
    secure: always

  - url: /.*
    script: auto
    secure: always

includes:
  - include: "*.json"
  - include: "*.yaml"
  - include: "*.yml"