# Generated by Django 5.2.1 on 2025-08-20 12:24

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('supabase_user_id', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('role', models.CharField(default='professional', max_length=50)),
                ('organization', models.CharField(blank=True, max_length=200, null=True)),
                ('license_number', models.CharField(blank=True, max_length=100, null=True)),
                ('specialization', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('email_verified', models.BooleanField(default=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users',
                'indexes': [models.Index(fields=['supabase_user_id'], name='users_supabas_e2a624_idx'), models.Index(fields=['email'], name='users_email_4b85f2_idx'), models.Index(fields=['is_active'], name='users_is_acti_847b48_idx')],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('paternal_last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('maternal_last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('masculine', 'Masculino'), ('feminine', 'Femenino'), ('other', 'Otro')], max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True)),
                ('country', models.CharField(default='México', max_length=100)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100, null=True)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('emergency_contact_relationship', models.CharField(blank=True, max_length=50, null=True)),
                ('insurance_provider', models.CharField(blank=True, max_length=100, null=True)),
                ('insurance_number', models.CharField(blank=True, max_length=100, null=True)),
                ('allergies', models.TextField(blank=True, null=True)),
                ('current_medications', models.TextField(blank=True, null=True)),
                ('chronic_conditions', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patients_created', to='expedix.user')),
            ],
            options={
                'db_table': 'patients',
            },
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('consultation_date', models.DateTimeField()),
                ('reason', models.CharField(blank=True, max_length=200, null=True)),
                ('consultation_notes', models.TextField(blank=True, null=True)),
                ('diagnosis', models.TextField(blank=True, null=True)),
                ('treatment_plan', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Programada'), ('in_progress', 'En Progreso'), ('completed', 'Completada'), ('cancelled', 'Cancelada')], default='scheduled', max_length=20)),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='expedix.patient')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultations', to='expedix.user')),
            ],
            options={
                'db_table': 'consultations',
            },
        ),
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('condition', models.CharField(max_length=200)),
                ('diagnosis_date', models.DateField(blank=True, null=True)),
                ('treatment', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='active', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_history', to='expedix.patient')),
            ],
            options={
                'db_table': 'medical_history',
                'indexes': [models.Index(fields=['patient'], name='medical_his_patient_cba0c9_idx'), models.Index(fields=['status'], name='medical_his_status_a1f2c0_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['email'], name='patients_email_bf0efb_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['is_active'], name='patients_is_acti_4a96f9_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['created_at'], name='patients_created_b2d3e4_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['created_by'], name='patients_created_0269d8_idx'),
        ),
        migrations.AddIndex(
            model_name='consultation',
            index=models.Index(fields=['patient'], name='consultatio_patient_fe04c5_idx'),
        ),
        migrations.AddIndex(
            model_name='consultation',
            index=models.Index(fields=['professional'], name='consultatio_profess_62dc89_idx'),
        ),
        migrations.AddIndex(
            model_name='consultation',
            index=models.Index(fields=['consultation_date'], name='consultatio_consult_98081f_idx'),
        ),
        migrations.AddIndex(
            model_name='consultation',
            index=models.Index(fields=['status'], name='consultatio_status_beb187_idx'),
        ),
    ]
