# Generated by Django 4.2.11 on 2025-08-24 18:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import expedix.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expedix', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient_id', models.UUIDField()),
                ('professional_id', models.UUIDField()),
                ('consultation_date', models.DateTimeField()),
                ('chief_complaint', models.TextField(blank=True, null=True)),
                ('consultation_notes', models.TextField(blank=True, null=True)),
                ('diagnosis', models.TextField(blank=True, null=True)),
                ('treatment_plan', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Programada'), ('in_progress', 'En Progreso'), ('completed', 'Completada'), ('cancelled', 'Cancelada')], default='scheduled', max_length=20)),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'consultations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('medical_record_number', models.TextField(blank=True, null=True)),
                ('first_name', models.TextField()),
                ('last_name', models.TextField(blank=True, null=True)),
                ('paternal_last_name', models.TextField(blank=True, null=True)),
                ('maternal_last_name', models.TextField(blank=True, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('phone', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.TextField(blank=True, null=True)),
                ('state', models.TextField(blank=True, null=True)),
                ('postal_code', models.TextField(blank=True, null=True)),
                ('country', models.TextField(blank=True, null=True)),
                ('curp', models.TextField(blank=True, null=True)),
                ('rfc', models.TextField(blank=True, null=True)),
                ('blood_type', models.TextField(blank=True, null=True)),
                ('allergies', expedix.models.SafeJSONField(blank=True, default=list, null=True)),
                ('chronic_conditions', expedix.models.SafeJSONField(blank=True, default=list, null=True)),
                ('current_medications', expedix.models.SafeJSONField(blank=True, default=list, null=True)),
                ('tags', expedix.models.SafeJSONField(blank=True, default=list, null=True)),
                ('emergency_contact_name', models.TextField(blank=True, null=True)),
                ('emergency_contact_phone', models.TextField(blank=True, null=True)),
                ('emergency_contact_relationship', models.TextField(blank=True, null=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=255, null=True)),
                ('emergency_phone', models.CharField(blank=True, max_length=255, null=True)),
                ('marital_status', models.CharField(blank=True, max_length=255, null=True)),
                ('occupation', models.CharField(blank=True, max_length=255, null=True)),
                ('insurance_provider', models.CharField(blank=True, max_length=255, null=True)),
                ('insurance_number', models.CharField(blank=True, max_length=255, null=True)),
                ('consent_to_treatment', models.BooleanField(blank=True, null=True)),
                ('consent_to_data_processing', models.BooleanField(blank=True, null=True)),
                ('patient_category', models.TextField(blank=True, null=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('clinic_id', models.UUIDField()),
                ('assigned_professional_id', models.UUIDField(blank=True, null=True)),
                ('workspace_id', models.UUIDField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'patients',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient_id', models.UUIDField()),
                ('professional_id', models.UUIDField()),
                ('consultation_id', models.UUIDField(blank=True, null=True)),
                ('prescription_date', models.DateTimeField(auto_now_add=True)),
                ('medications', models.JSONField(default=list)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('issued', 'Emitida'), ('dispensed', 'Dispensada'), ('cancelled', 'Cancelada')], default='draft', max_length=20)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'prescriptions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('supabase_user_id', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('role', models.CharField(default='professional', max_length=50)),
                ('organization', models.CharField(blank=True, max_length=200, null=True)),
                ('license_number', models.CharField(blank=True, max_length=100, null=True)),
                ('specialization', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('email_verified', models.BooleanField(default=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users',
                'indexes': [models.Index(fields=['supabase_user_id'], name='users_supabas_e2a624_idx'), models.Index(fields=['email'], name='users_email_4b85f2_idx'), models.Index(fields=['is_active'], name='users_is_acti_847b48_idx')],
            },
        ),
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('condition', models.CharField(max_length=200)),
                ('diagnosis_date', models.DateField(blank=True, null=True)),
                ('treatment', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='active', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_history', to='expedix.patient')),
            ],
            options={
                'db_table': 'medical_history',
                'indexes': [models.Index(fields=['patient'], name='medical_his_patient_cba0c9_idx'), models.Index(fields=['status'], name='medical_his_status_a1f2c0_idx')],
            },
        ),
    ]
