# Generated by Django 4.2.11 on 2025-08-25 14:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('expedix', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('clinic_id', models.UUIDField(blank=True, null=True)),
                ('workspace_id', models.UUIDField(blank=True, null=True)),
                ('created_by', models.UUIDField()),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('template_type', models.CharField(choices=[('general', 'Consulta General'), ('followup', 'Consulta de Seguimiento'), ('initial', 'Primera Consulta'), ('emergency', 'Consulta de Emergencia'), ('specialized', 'Consulta Especializada'), ('custom', 'Plantilla Personalizada')], default='general', max_length=20)),
                ('formx_template_id', models.UUIDField(blank=True, help_text='ID del template en FormX', null=True)),
                ('fields_config', models.JSONField(default=list, help_text='Configuración de campos si no usa FormX')),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'consultation_templates',
            },
        ),
        migrations.AlterModelOptions(
            name='prescription',
            options={'ordering': ['-date_prescribed']},
        ),
        migrations.CreateModel(
            name='ExpedixConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('clinic_id', models.UUIDField(blank=True, null=True)),
                ('workspace_id', models.UUIDField(blank=True, null=True)),
                ('user_id', models.UUIDField()),
                ('configuration_type', models.CharField(choices=[('clinic', 'Configuración de Clínica'), ('individual', 'Configuración Individual')], default='clinic', max_length=20)),
                ('required_patient_fields', models.JSONField(default=list, help_text='Campos obligatorios para pacientes')),
                ('optional_patient_fields', models.JSONField(default=list, help_text='Campos opcionales disponibles')),
                ('custom_patient_fields', models.JSONField(default=list, help_text='Campos personalizados definidos por la clínica')),
                ('consultation_templates_enabled', models.BooleanField(default=True)),
                ('default_consultation_template', models.UUIDField(blank=True, null=True)),
                ('settings', models.JSONField(default=dict, help_text='Configuraciones adicionales')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'expedix_configurations',
                'indexes': [models.Index(fields=['clinic_id'], name='expedix_con_clinic__db5876_idx'), models.Index(fields=['workspace_id'], name='expedix_con_workspa_bddce7_idx'), models.Index(fields=['user_id'], name='expedix_con_user_id_b7b374_idx'), models.Index(fields=['configuration_type'], name='expedix_con_configu_7993bb_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='expedixconfiguration',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('clinic_id__isnull', False), ('workspace_id__isnull', True)), models.Q(('clinic_id__isnull', True), ('workspace_id__isnull', False)), _connector='OR'), name='expedix_config_dual_system_constraint'),
        ),
        migrations.AddConstraint(
            model_name='expedixconfiguration',
            constraint=models.UniqueConstraint(condition=models.Q(('clinic_id__isnull', False)), fields=('clinic_id',), name='unique_clinic_config'),
        ),
        migrations.AddConstraint(
            model_name='expedixconfiguration',
            constraint=models.UniqueConstraint(condition=models.Q(('workspace_id__isnull', False)), fields=('workspace_id',), name='unique_workspace_config'),
        ),
        migrations.AddIndex(
            model_name='consultationtemplate',
            index=models.Index(fields=['clinic_id'], name='consultatio_clinic__36b183_idx'),
        ),
        migrations.AddIndex(
            model_name='consultationtemplate',
            index=models.Index(fields=['workspace_id'], name='consultatio_workspa_0a3316_idx'),
        ),
        migrations.AddIndex(
            model_name='consultationtemplate',
            index=models.Index(fields=['created_by'], name='consultatio_created_ccf154_idx'),
        ),
        migrations.AddIndex(
            model_name='consultationtemplate',
            index=models.Index(fields=['template_type'], name='consultatio_templat_c795fd_idx'),
        ),
        migrations.AddIndex(
            model_name='consultationtemplate',
            index=models.Index(fields=['is_active'], name='consultatio_is_acti_5e63d4_idx'),
        ),
        migrations.AddConstraint(
            model_name='consultationtemplate',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('clinic_id__isnull', False), ('workspace_id__isnull', True)), models.Q(('clinic_id__isnull', True), ('workspace_id__isnull', False)), _connector='OR'), name='consultation_template_dual_system_constraint'),
        ),
    ]
