# Generated by Django 4.2.11 on 2025-09-13 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedix', '0003_add_consultation_templates'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationDatabase',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('commercial_name', models.TextField(blank=True, null=True)),
                ('generic_name', models.TextField(blank=True, null=True)),
                ('active_ingredients', models.TextField(blank=True, null=True)),
                ('concentration', models.TextField(blank=True, null=True)),
                ('pharmaceutical_form', models.TextField(blank=True, null=True)),
                ('laboratory', models.TextField(blank=True, null=True)),
                ('control_group', models.TextField(blank=True, null=True)),
                ('therapeutic_indications', models.TextField(blank=True, null=True)),
                ('contraindications', models.TextField(blank=True, null=True)),
                ('side_effects', models.TextField(blank=True, null=True)),
                ('dosage_recommendations', models.TextField(blank=True, null=True)),
                ('storage_conditions', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'medication_database',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PrescriptionMedication',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('prescription_id', models.UUIDField(blank=True, null=True)),
                ('patient_id', models.UUIDField(blank=True, null=True)),
                ('consultation_id', models.UUIDField(blank=True, null=True)),
                ('professional_id', models.UUIDField(blank=True, null=True)),
                ('medication_database_id', models.UUIDField(blank=True, null=True)),
                ('medication_name', models.TextField(blank=True, null=True)),
                ('generic_name', models.TextField(blank=True, null=True)),
                ('concentration', models.TextField(blank=True, null=True)),
                ('pharmaceutical_form', models.TextField(blank=True, null=True)),
                ('dosage', models.TextField(blank=True, null=True)),
                ('frequency', models.TextField(blank=True, null=True)),
                ('duration', models.TextField(blank=True, null=True)),
                ('special_instructions', models.TextField(blank=True, null=True)),
                ('medical_indication', models.TextField(blank=True, null=True)),
                ('clinic_id', models.BooleanField(blank=True, null=True)),
                ('user_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'prescription_medications',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('email', models.TextField(blank=True, null=True)),
                ('first_name', models.TextField(blank=True, null=True)),
                ('last_name', models.TextField(blank=True, null=True)),
                ('license_type', models.TextField(blank=True, null=True)),
                ('clinic_id', models.UUIDField(blank=True, null=True)),
                ('clinic_role', models.TextField(blank=True, null=True)),
                ('professional_title', models.TextField(blank=True, null=True)),
                ('license_number', models.TextField(blank=True, null=True)),
                ('specialization', models.TextField(blank=True, null=True)),
                ('phone', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'profiles',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterModelOptions(
            name='prescription',
            options={'managed': False},
        ),
        migrations.RemoveConstraint(
            model_name='consultationtemplate',
            name='consultation_template_dual_system_constraint',
        ),
        migrations.RemoveConstraint(
            model_name='expedixconfiguration',
            name='expedix_config_dual_system_constraint',
        ),
        migrations.RemoveConstraint(
            model_name='expedixconfiguration',
            name='unique_clinic_config',
        ),
        migrations.RemoveConstraint(
            model_name='expedixconfiguration',
            name='unique_workspace_config',
        ),
        migrations.RemoveIndex(
            model_name='consultationtemplate',
            name='consultatio_workspa_0a3316_idx',
        ),
        migrations.RemoveIndex(
            model_name='expedixconfiguration',
            name='expedix_con_workspa_bddce7_idx',
        ),
        migrations.RemoveField(
            model_name='consultationtemplate',
            name='workspace_id',
        ),
        migrations.RemoveField(
            model_name='expedixconfiguration',
            name='workspace_id',
        ),
        migrations.AddField(
            model_name='consultationtemplate',
            name='user_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consultationtemplate',
            name='clinic_id',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='expedixconfiguration',
            name='clinic_id',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='consultationtemplate',
            index=models.Index(fields=['user_id'], name='consultatio_user_id_571576_idx'),
        ),
        migrations.AddConstraint(
            model_name='expedixconfiguration',
            constraint=models.UniqueConstraint(fields=('user_id',), name='unique_user_config'),
        ),
    ]
