# Generated by Django 4.2.11 on 2025-11-15 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expedix', '0004_link_patient_user_id_state_only'),
        ('expedix', '0004_medicationdatabase_prescriptionmedication_profile_and_more'),
    ]

    operations = [
    ]
