# Generated by Django 4.2.11 on 2025-11-15 20:31

from django.db import migrations, models
import expedix.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('expedix', '0005_merge_20251115_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('clinic_id', models.UUIDField(blank=True, null=True)),
                ('workingDays', models.JSONField(blank=True, default=expedix.models.default_working_days)),
                ('workingHours', models.JSONField(blank=True, default=expedix.models.default_working_hours)),
                ('defaultAppointmentDuration', models.IntegerField(default=60)),
                ('bufferTime', models.IntegerField(default=15)),
                ('lunchBreak', models.JSONField(blank=True, default=expedix.models.default_lunch_break)),
                ('consultationTypes', models.JSONField(blank=True, default=expedix.models.default_consultation_types)),
                ('work_days', models.JSONField(blank=True, default=expedix.models.default_work_days)),
                ('start_time', models.CharField(default='08:00', max_length=5)),
                ('end_time', models.CharField(default='20:00', max_length=5)),
                ('appointment_duration', models.IntegerField(default=60)),
                ('break_time', models.IntegerField(default=15)),
                ('lunch_start', models.CharField(default='13:00', max_length=5)),
                ('lunch_end', models.CharField(default='14:00', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('user_id', 'clinic_id')},
            },
        ),
    ]
