[phases.setup]
nixPkgs = ['nodejs_18', 'npm-9_x']

[phases.install]
cmds = ['npm ci']

[phases.build]
cmds = [
  'npx prisma generate',
  'ls -la shared/validators/',
  'find . -name "*.json" | head -20'
]

[start]
cmd = 'npm start'