# Generated by Django 5.2.1 on 2025-08-17 18:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Documento')),
                ('document_type', models.CharField(choices=[('consent', 'Consentimiento Informado'), ('privacy', 'Aviso de Privacidad'), ('therapeutic', 'Acuerdo Terapéutico'), ('policy', 'Política de Atención'), ('appointment', 'Confirmación de Cita'), ('follow_up', 'Seguimiento Post-Consulta'), ('birthday', 'Felicitación de Cumpleaños'), ('survey', 'Encuesta de Calidad')], max_length=20, verbose_name='Tipo de Documento')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('template_content', models.TextField(help_text='Contenido HTML con placeholders como {{patient_name}}, {{date}}, etc.', verbose_name='Contenido del Template')),
                ('auto_fill_fields', models.JSONField(default=list, help_text='Lista de campos que se llenan automáticamente desde Expedix', verbose_name='Campos Auto-llenables')),
                ('requires_signature', models.BooleanField(default=False, verbose_name='Requiere Firma')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_default', models.BooleanField(default=False, verbose_name='Por Defecto')),
                ('email_subject', models.CharField(blank=True, max_length=200, verbose_name='Asunto del Email')),
                ('email_body', models.TextField(blank=True, verbose_name='Cuerpo del Email')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plantilla de Documento',
                'verbose_name_plural': 'Plantillas de Documentos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FormTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Formulario')),
                ('form_type', models.CharField(choices=[('clinical', 'Formulario Clínico'), ('document', 'Documento Legal'), ('survey', 'Encuesta/Seguimiento'), ('intake', 'Formulario de Admisión'), ('consent', 'Consentimiento Informado'), ('follow_up', 'Seguimiento Post-Consulta')], max_length=20, verbose_name='Tipo')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('integration_type', models.CharField(choices=[('expedix', 'Expedix - Expedientes Médicos'), ('clinimetrix', 'ClinimetrixPro - Evaluaciones'), ('standalone', 'Independiente')], default='expedix', max_length=20, verbose_name='Integración')),
                ('is_default', models.BooleanField(default=False, verbose_name='Formulario por Defecto')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('requires_auth', models.BooleanField(default=False, verbose_name='Requiere Autenticación')),
                ('mobile_optimized', models.BooleanField(default=True, verbose_name='Optimizado para Móvil')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auto_sync_expedix', models.BooleanField(default=True, verbose_name='Auto-Sync con Expedix')),
                ('expedix_mapping', models.JSONField(default=dict, help_text='Mapeo automático de campos del formulario a campos de Expedix', verbose_name='Mapeo de Campos Expedix')),
                ('email_template', models.TextField(blank=True, verbose_name='Template de Email')),
                ('success_message', models.TextField(blank=True, verbose_name='Mensaje de Éxito')),
                ('redirect_url', models.URLField(blank=True, verbose_name='URL de Redirección')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_forms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plantilla de Formulario',
                'verbose_name_plural': 'Plantillas de Formularios',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient_id', models.CharField(max_length=100, verbose_name='ID Paciente Supabase')),
                ('patient_email', models.EmailField(blank=True, max_length=254, verbose_name='Email del Paciente')),
                ('access_token', models.CharField(max_length=100, unique=True, verbose_name='Token de Acceso')),
                ('form_data', models.JSONField(default=dict, verbose_name='Datos del Formulario')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Envío')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('device_type', models.CharField(blank=True, max_length=50, verbose_name='Tipo de Dispositivo')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('submitted', 'Enviado'), ('processed', 'Procesado'), ('synced', 'Sincronizado'), ('error', 'Error')], default='draft', max_length=20, verbose_name='Estado')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Procesado')),
                ('synced_to_expedix', models.BooleanField(default=False, verbose_name='Sincronizado con Expedix')),
                ('expedix_sync_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Sync Expedix')),
                ('processing_notes', models.TextField(blank=True, verbose_name='Notas de Procesamiento')),
                ('error_message', models.TextField(blank=True, verbose_name='Mensaje de Error')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='formx.formtemplate')),
            ],
            options={
                'verbose_name': 'Respuesta de Formulario',
                'verbose_name_plural': 'Respuestas de Formularios',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100, verbose_name='Nombre del Campo')),
                ('field_type', models.CharField(choices=[('text', 'Texto Corto'), ('textarea', 'Texto Largo'), ('email', 'Correo Electrónico'), ('phone', 'Teléfono'), ('number', 'Número'), ('decimal', 'Número Decimal'), ('date', 'Fecha'), ('datetime', 'Fecha y Hora'), ('time', 'Hora'), ('select', 'Lista Desplegable'), ('radio', 'Selección Única (Radio)'), ('checkbox', 'Selección Múltiple'), ('boolean', 'Sí/No (Checkbox)'), ('file', 'Archivo'), ('image', 'Imagen'), ('name', 'Nombre Completo'), ('address', 'Dirección'), ('city', 'Ciudad'), ('insurance', 'Seguro Médico'), ('emergency_contact', 'Contacto de Emergencia'), ('signature', 'Firma Digital'), ('rating', 'Calificación (1-5)'), ('scale', 'Escala (1-10)')], max_length=20, verbose_name='Tipo de Campo')),
                ('label', models.CharField(max_length=200, verbose_name='Etiqueta')),
                ('help_text', models.TextField(blank=True, verbose_name='Texto de Ayuda')),
                ('placeholder', models.CharField(blank=True, max_length=200, verbose_name='Placeholder')),
                ('required', models.BooleanField(default=False, verbose_name='Obligatorio')),
                ('min_length', models.PositiveIntegerField(blank=True, null=True, verbose_name='Longitud Mínima')),
                ('max_length', models.PositiveIntegerField(blank=True, null=True, verbose_name='Longitud Máxima')),
                ('min_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Mínimo')),
                ('max_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Máximo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('css_classes', models.CharField(blank=True, max_length=200, verbose_name='Clases CSS')),
                ('choices', models.JSONField(blank=True, default=list, help_text='Lista de opciones para campos de selección', verbose_name='Opciones')),
                ('show_conditions', models.JSONField(blank=True, default=dict, help_text='Cuándo mostrar este campo basado en otros campos', verbose_name='Condiciones de Visibilidad')),
                ('validation_rules', models.JSONField(blank=True, default=dict, help_text='Validaciones personalizadas', verbose_name='Reglas de Validación')),
                ('expedix_field', models.CharField(blank=True, help_text='Campo correspondiente en Expedix para auto-sync', max_length=100, verbose_name='Campo de Expedix')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='formx.formtemplate')),
            ],
            options={
                'verbose_name': 'Campo de Formulario',
                'verbose_name_plural': 'Campos de Formulario',
                'ordering': ['order'],
                'unique_together': {('template', 'field_name')},
            },
        ),
    ]
