# defaults.py
DEFAULT_MENTAL_EXAM = {
  "apariencia": {
    "aspecto_general": "Adecuado",
    "higiene": "Buena",
    "vestimenta": "Apropiada para contexto",
    "edad_aparente": "Aparenta edad cronológica",
    "complexion": "Normal",
    "facies": "Normal",
    "caracteristicas_distintivas": "",
  },
  "conducta": {
    "nivel_psicomotor": "Normal",
    "contacto_visual": "Adecuado",
    "postura": "Normal / Relajada",
    "marcha": "Normal",
    "movimientos_anormales": "Ninguno",
    "cooperacion_entrevista": "Cooperador",
  },
  "actitud": {"actitud_general": "Colaboradora", "rapport": "Fácil de establecer"},
  "habla": {
    "velocidad": "Normal",
    "volumen": "Normal",
    "tono": "Normal",
    "articulacion": "Clara",
    "cantidad": "Normal",
    "latencia_respuesta": "Normal",
    "prosodia": "Normal",
  },
  "afecto": {
    "tipo": "Eutímico",
    "rango_afectivo": "Normal",
    "intensidad": "Normal",
    "reactividad": "Reactivo",
    "congruencia": "Congruente",
    "estabilidad": "Estable",
  },
  "animo": {"estado_animo": "", "nivel": 5, "concordancia_animo_afecto": "Concordante"},
  "pensamiento_proceso": {
    "curso_pensamiento": "Lógico y coherente",
    "velocidad_pensamiento": "Normal",
    "contenido_discurso": "Apropiado y relevante",
  },
  "pensamiento_contenido": {
    "ideas_muerte": "Ausentes",
    "ideacion_suicida": "Ausente",
    "plan_suicida": "",
    "ideacion_homicida": "Ausente",
    "delirios": [],
    "caracteristicas_delirios": "No aplica",
    "ideas_sobrevaloradas": "Ausentes",
    "obsesiones": "Ausentes",
    "tipo_obsesiones": [],
    "compulsiones": "Ausentes",
    "tipo_compulsiones": [],
    "fobias": "Ausentes",
    "preocupaciones_excesivas": "Ausentes",
  },
  "percepcion": {
    "alucinaciones_auditivas": "Ausentes",
    "alucinaciones_auditivas_caracteristicas": "",
    "alucinaciones_visuales": "Ausentes",
    "alucinaciones_visuales_caracteristicas": "",
    "alucinaciones_tactiles": "Ausentes",
    "alucinaciones_tactiles_caracteristicas": "",
    "alucinaciones_olfatorias": "Ausentes",
    "alucinaciones_olfatorias_caracteristicas": "",
    "alucinaciones_gustativas": "Ausentes",
    "alucinaciones_gustativas_caracteristicas": "",
    "ilusiones": "Ausentes",
    "ilusiones_caracteristicas": "",
    "despersonalizacion": "Ausente",
    "despersonalizacion_caracteristicas": "",
    "desrealizacion": "Ausente",
    "desrealizacion_caracteristicas": "",
  },
  "cognicion": {
    "nivel_conciencia": "Alerta",
    "orientacion_persona": "Orientado",
    "orientacion_lugar": "Orientado",
    "orientacion_tiempo": "Orientado",
    "orientacion_situacion": "Orientado",
    "atencion": "Normal",
    "concentracion": "Adecuada",
    "memoria_inmediata": "Conservada",
    "memoria_reciente": "Conservada",
    "memoria_remota": "Conservada",
    "capacidad_abstracta": "Normal",
    "calculo": "Conservado",
    "inteligencia_clinica_estimada": "Normal",
    "funciones_ejecutivas": "Sin alteraciones aparentes",
  },
  "insight_juicio": {
    "insight": "Completo",
    "grado": "",
    "juicio": "Conservado",
    "juicio_social": "Adecuado",
    "control_impulsos": "Adecuado",
  },
  "funcionalidad": {
    "nivel_global": 100,
    "laboral_escolar": "Sin afectación",
    "funcionalidad_social": "Sin afectación",
    "autocuidado": "Independiente",
  },
}
